export const ADD = 'ADD';
export const GET_HOME_INFO = 'GET_HOME_INFO';

export const REQUEST_USERS = 'REQUEST_USERS';
export const REQUEST_USERS_SUCCESS = 'REQUEST_USERS_SUCCESS';
export const REQUEST_USERS_FAIL = 'REQUEST_USERS_FAIL';

export const REQUEST_USER_REGISTER = "REQUEST_USER_REGISTER";
export const REQUEST_USER_REGISTER_FAIL = "REQUEST_USER_FAIL";

export const REQUEST_USER_LOGIN = "REQUEST_USER_LOGIN";
export const USER_HAS_TOKEN = "USER_HAS_TOKEN";
export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";

export const LOCALE_SET = "LOCALE_SET";

export const REQUEST_CHECKOUT_PAYPAL = 'REQUEST_CHECKOUT_PAYPAL';
export const CHECKOUT_PAYPAL_SUCCESS = 'CHECKOUT_PAYPAL_SUCCESS';
export const CHECKOUT_PAYPAL_FAIL = 'CHECKOUT_PAYPAL_FAIL';